// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Topeexample.proto

package CinemaIntelligent;

public final class TopeMessageService {
  private TopeMessageService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaIntelligent_ActivateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaIntelligent_ActivateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaIntelligent_ActivateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaIntelligent_ActivateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Topeexample.proto\022\021CinemaIntelligent\"\037" +
      "\n\017ActivateRequest\022\014\n\004name\030\001 \001(\t\"#\n\020Activ" +
      "ateResponse\022\017\n\007message\030\001 \001(\t2k\n\017CinemaIm" +
      "mersive\022X\n\013TopeMessage\022\".CinemaIntellige" +
      "nt.ActivateRequest\032#.CinemaIntelligent.A" +
      "ctivateResponse\"\000B)\n\021CinemaIntelligentB\022" +
      "TopeMessageServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CinemaIntelligent_ActivateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CinemaIntelligent_ActivateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaIntelligent_ActivateRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_CinemaIntelligent_ActivateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CinemaIntelligent_ActivateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaIntelligent_ActivateResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
