// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S01.proto

package S01Seat_Heating;

public interface ActivateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Artifact_cinema.ActivateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of the seat to be heated.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of the seat to be heated.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
