// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S01.proto

package S01Seat_Heating;

public final class Serv01Seat_Heating {
  private Serv01Seat_Heating() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Artifact_cinema_ActivateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Artifact_cinema_ActivateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Artifact_cinema_ActivateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Artifact_cinema_ActivateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tS01.proto\022\017Artifact_cinema\"\037\n\017Activate" +
      "Request\022\014\n\004name\030\001 \001(\t\"#\n\020ActivateRespons" +
      "e\022\017\n\007message\030\001 \001(\t2k\n\017CinemaImmersive\022X\n" +
      "\017ActivateHeating\022 .Artifact_cinema.Activ" +
      "ateRequest\032!.Artifact_cinema.ActivateRes" +
      "ponse\"\000B\'\n\017S01Seat_HeatingB\022Serv01Seat_H" +
      "eatingP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Artifact_cinema_ActivateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Artifact_cinema_ActivateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Artifact_cinema_ActivateRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_Artifact_cinema_ActivateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Artifact_cinema_ActivateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Artifact_cinema_ActivateResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
