// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S1_SeatHeating.proto

package S01SeatHeating;

public interface ActivateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaIntelligent.ActivateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Confirmation message.
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Confirmation message.
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
