// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S04.proto

package S04Cinema_Entrance;

public interface TicketResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Artifact_cinema.TicketResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Message indicating whether the ticket was accepted or rejected
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Message indicating whether the ticket was accepted or rejected
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
