// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S04.proto

package S04Cinema_Entrance;

public interface TicketRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Artifact_cinema.TicketRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Ticket number and client's name
   * </pre>
   *
   * <code>string ticket_number = 1;</code>
   */
  java.lang.String getTicketNumber();
  /**
   * <pre>
   * Ticket number and client's name
   * </pre>
   *
   * <code>string ticket_number = 1;</code>
   */
  com.google.protobuf.ByteString
      getTicketNumberBytes();

  /**
   * <code>string client_name = 2;</code>
   */
  java.lang.String getClientName();
  /**
   * <code>string client_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientNameBytes();
}
