// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S04.proto

package S04Cinema_Entrance;

public final class Serv04Cinema_Entrance {
  private Serv04Cinema_Entrance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Artifact_cinema_TicketRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Artifact_cinema_TicketRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Artifact_cinema_TicketResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Artifact_cinema_TicketResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tS04.proto\022\017Artifact_cinema\";\n\rTicketRe" +
      "quest\022\025\n\rticket_number\030\001 \001(\t\022\023\n\013client_n" +
      "ame\030\002 \001(\t\"!\n\016TicketResponse\022\017\n\007message\030\001" +
      " \001(\t2d\n\rTicketService\022S\n\014AdmitTickets\022\036." +
      "Artifact_cinema.TicketRequest\032\037.Artifact" +
      "_cinema.TicketResponse(\0010\001B-\n\022S04Cinema_" +
      "EntranceB\025Serv04Cinema_EntranceP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Artifact_cinema_TicketRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Artifact_cinema_TicketRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Artifact_cinema_TicketRequest_descriptor,
        new java.lang.String[] { "TicketNumber", "ClientName", });
    internal_static_Artifact_cinema_TicketResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Artifact_cinema_TicketResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Artifact_cinema_TicketResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
