// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S02.proto

package S02Seat_Water;

public interface ActivateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:artifact_cinema.ActivateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string on = 1;</code>
   */
  java.lang.String getOn();
  /**
   * <code>string on = 1;</code>
   */
  com.google.protobuf.ByteString
      getOnBytes();
}
