// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S03.proto

package S03Cinema_Lights;

public interface LightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:S03Cinema_lights.LightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Cinema room number
   * </pre>
   *
   * <code>string room_number = 1;</code>
   */
  java.lang.String getRoomNumber();
  /**
   * <pre>
   * Cinema room number
   * </pre>
   *
   * <code>string room_number = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomNumberBytes();

  /**
   * <pre>
   * Command to either activate or turn off lights
   * </pre>
   *
   * <code>string command = 2;</code>
   */
  java.lang.String getCommand();
  /**
   * <pre>
   * Command to either activate or turn off lights
   * </pre>
   *
   * <code>string command = 2;</code>
   */
  com.google.protobuf.ByteString
      getCommandBytes();
}
