// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S01.proto

package S01Seat_Heating;

public interface ActivateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Artifact_cinema.ActivateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Confirmation message.
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Confirmation message.
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
